version: 1.0.{build}
clone_depth: 1
clone_folder: c:\projects\app

environment:
    matrix:
        - PY: 27
        - PY: 36
        - STYLE: 1

install:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))

build_script:
    - ci\win_set_python.bat
    - ci\win_install.bat
    - ci\win_style.bat
    - ci\win_tests.bat
